name: 'build'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Read version from file and set as env var
        id: set_version
        run: echo "TAG_VERSION=$(cat .devcontainer/platform_version.txt)" >> $GITHUB_ENV

      - name: Display version
        run: echo "Version is $TAG_VERSION"

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Login to dockerhub Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to nexus Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.weslyg.ru
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build Dev Container for nexus
        uses: devcontainers/ci@v0.3
        with:
          #imageTag: $TAG_VERSION
          imageName: registry.weslyg.ru/ansible-infra
          platform: linux/amd64,linux/arm64
          push: always
          cacheFrom: registry.weslyg.ru/ansible-infra
          # runCmd: |
          #   # Add multiple commands to run if needed
          #   make install-packages
          #   make ci-build

      - name: Build Dev Container for dockerhub
        uses: devcontainers/ci@v0.3
        with:
          #imageTag: $TAG_VERSION
          imageName: docker.io/weslyg/ansible-infra
          cacheFrom: docker.io/weslyg/ansible-infra
          platform: linux/amd64,linux/arm64
          push: always